name: EnvironmentFindByProjectId

authors:
  - Humera Sultana

type: SUITE

endpoint:  /envs/project-id/{{@CreateProject_Response.data.id}}

method: GET

auth: Default

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"

severity: Major

category: Functional

tags:
    - V2

policies:
   logger: DEBUG
