name: EnvironmentRating

authors:
  - Humera Sultana

type: SUITE

init:
   - CreateEnvironment

endpoint: /envs/{{@CreateEnvironment_Response.data}}/envrating

method: GET

auth: Default

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"

severity: Major

category: Functional

tags:
    - V2

policies:
  logger: DEBUG
