name: EnvironmentFindById

authors:
  - Humera Sultana

type: SUITE

init:
  - CreateEnvironment

endpoint: /alerts/{{@CreateEnvironment_Response.data.id}}?page=0&pageSize=20

method: GET

auth: Default

headers:
  - 'Content-Type: application/json'

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"

severity: Major

category: Functional

tags:
   - V2

policies:
  logger: DEBUG
